name: Publish
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Type of version bump'
        required: true
        default: 'minor'
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node
      uses: actions/setup-node@v2.1.5
      with:
        node-version: '16'
        registry-url: 'https://registry.npmjs.org'
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Dependencies
      run: npm install
    - name: Bump Version
      run: |
        git config --global user.name 'Naitik Shah'
        git config --global user.email 'daaku@users.noreply.github.com'
        npm version ${{ github.event.inputs.version }}
        git push && git push --tags
    - name: Publish
      run: npm run deploy
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
